config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'users/:id', to: 'users#show', as: 'user'

  resources :articles do
    resources :comments
  end

  root 'articles#index'

  # Static pages
  get  '/about', to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { minimum: 5 }
  validates :url,
            format: { with: URI::regexp(%w(http https)),
                      allow_blank: true,
                      message: "\"%{value}\" does't seem like a valid URL" }
  validates :url, presence: true, if: "text.blank?"
  validates :text, presence: true, if: "url.blank?"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user

  validates :body, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]

  def index
    @articles = Article.all.order(created_at: :desc)
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params.merge(user: current_user))

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :text, :url)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.build(comment_params)
    @comment.user = current_user

    @article.save

    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy

    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    # TODO: This should require the user to be logged in
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<% provide(:title, 'Edit Article') %>
<h1>Edit Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<% provide(:title, 'Home') %>

<table class="itemlist" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef">
  <tbody>
    <% @articles.each_with_index do |article, index|  %>
      <tr class="athing">
        <td align="right" valign="top" class="title">
          <span class="rank"><%= index + 1 %>.</span>
        </td>
        <td valign="top" class="votelinks">
          <center>
            <!-- TODO: Create an onclick event here -->
            <span class="glyphicon glyphicon-chevron-up" title="upvote"></span>
          </center>
        </td>
        <td class="title">
          <% if article.url.blank? %>
            <%= link_to article.title, article %>
          <% else %>
            <%= link_to article.title, article.url %>
            (<%= URI(article.url).host.sub(/^www\./, '') %>)
          <% end %>
        </td>
      </tr>
      <tr>
        <td colspan="2"></td>
        <!-- <td><%= article.text %></td> -->
        <td class="subtext">
          <span class="score">100 points</span>
          by <%= link_to article.user.username, article.user %>
          <span class="age">
            <%= link_to time_ago_in_words(article.created_at) + " ago", article %>
          </span>
          |
          <%= link_to "#{article.comments.count} Comments", article %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/new.html.erb
<% provide(:title, 'New Article') %>
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<% provide(:title, @article.title) %>

<table border="0" >
  <tbody>
    <tr class="athing">
      <td align="right" valign="top" class="title">
        <span class="rank"></span>
      </td>
      <td valign="top" class="votelinks">
        <center>
          <!-- TODO: Create an onclick event here -->
          <span class="glyphicon glyphicon-chevron-up" title="upvote"></span>
        </center>
      </td>
      <td class="title">
        <% if @article.url.blank? %>
          <%= link_to @article.title, @article %>
        <% else %>
          <%= link_to @article.title, @article.url %>
          (<%= URI(@article.url).host.sub(/^www\./, '') %>)
        <% end %>
      </td>
    </tr>
    <tr>
      <td colspan="2"></td>
      <!-- <td><%= @article.text %></td> -->
      <td class="subtext">
        <span class="score">100 points</span>
        by <%= link_to @article.user.username, @article.user %>
        <span class="age">
          <%= link_to time_ago_in_words(@article.created_at) + " ago", @article %>
        </span>
        |
        <%= link_to "#{@article.comments.count} Comments", @article %>
      </td>
    </tr>
  </tbody>
</table>

<% if @article.text.present? %>
  <p>
    <strong>Text:</strong>
    <%= @article.text %>
  </p>
<% end %>

<h2>Comments:</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.user.username %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
  method: :delete,
  data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    A discussion-generating site for the Greek tech community.
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to 'athens tech city', root_path, id: 'logo' %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'About', about_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to 'Submit', new_article_path %></li>
          <li><%= link_to current_user.username, current_user %></li>
          <li><%= link_to 'Log Out', destroy_user_session_path,
              method: :delete %></li>
        <% else %>
          <li><%= link_to 'Log in', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_notice.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <a href="#" data-dismiss="alert" class="close">x</a>
    <ul>
      <li>
        <%= message %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield (:title) %> | Athens Tech City</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% puts flash.keys %>
      <%= render 'layouts/notice' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>
<p>
  We're a group of hack-hack-hackers.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Athens Tech City team. How? No idea!
</p>

app/views/users/show.html.erb
<% provide(:title, "Profile: #{@user.email}") %>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>